# Generated by Django 3.2.9 on 2021-12-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
