# Generated by Django 3.2.9 on 2021-12-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
